
spring:
  redis:
    port: 6379
    password:
    host: localhost
    timeToLive: 60
  thymeleaf:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: postgres
    password: Anurag*98
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  port: 8080


  amqp:
    deserialization:
      trust:
        all: true

clientId:
clientSecret:


rabbitmq:
  queue: indexing-queue-info7255
  exchange: spring-boot-exchange




